Repository boostcampwm2023/web09-MagicConch, pull requests merged in 2024-01, with the labels that each got.

#455 Be/refactor/#454 aws 마이그레이션
  .github/workflows/blue-green-cd.yml
  backend/Dockerfile.signal
  backend/Dockerfile.was
  backend/compose.blue-build.yml
  backend/compose.blue-deploy.yml
  backend/compose.green-build.yml
  backend/compose.green-deploy.yml
  backend/deploy.sh
  backend/was/src/common/config/database/database.module.ts
  backend/was/src/common/config/sentry.setting.ts
Labels: BE, DevOps, task, refactor

#459 Be/feature/#458 kakao OAuth
  backend/was/package-lock.json
  backend/was/package.json
  backend/was/src/app.controller.ts
  backend/was/src/app.module.ts
  backend/was/src/app.service.ts
  backend/was/src/auth/auth.controller.ts
  backend/was/src/auth/auth.module.ts
  backend/was/src/auth/dto/jwt-payload.dto.ts
  backend/was/src/auth/dto/kakao/kakao-access-token-info.dto.ts
  backend/was/src/auth/dto/kakao/kakao-token.dto.ts
  backend/was/src/auth/dto/oauth-token.dto.ts
  backend/was/src/auth/dto/profile.dto.ts
  backend/was/src/auth/guard/auth.guard.ts
  backend/was/src/auth/interface/cache-key.ts
  backend/was/src/auth/service/auth.service.ts
  backend/was/src/auth/service/kakao.auth.service.ts
  backend/was/src/auth/util/kakao.ts
  backend/was/src/chat/chat.controller.ts
  backend/was/src/common/auth/auth.guard.ts
  backend/was/src/common/config/cache/cache.module.ts
  backend/was/src/common/config/jwt/jwt.module.ts
  backend/was/src/common/constants/apis.ts
  backend/was/src/common/constants/errors.ts
  backend/was/src/common/constants/etc.ts
  backend/was/src/common/errors/jwt.error.ts
  backend/was/src/common/interceptors/errors.interceptor.ts
  backend/was/src/common/utils/logging.ts
  backend/was/src/common/utils/slack-webhook.ts
  backend/was/src/members/dto/create-member.dto.ts
  backend/was/src/members/dto/update-member.dto.ts
  backend/was/src/members/entities/member.entity.ts
  backend/was/src/members/members.service.ts
Labels: feature, BE

#464 Be/bugfix/#463 redis 연결 실패
  backend/was/src/app.module.ts
  backend/was/src/auth/auth.module.ts
  backend/was/src/common/config/cache/cache.module.ts
Labels: bug, BE

#468 Be/refactor/#467 graceful shutdown 보완
  backend/was/package-lock.json
  backend/was/package.json
  backend/was/src/app.module.ts
  backend/was/src/auth/auth.controller.ts
  backend/was/src/auth/auth.decorators.ts
  backend/was/src/auth/auth.module.ts
  backend/was/src/auth/dto/index.ts
  backend/was/src/auth/dto/kakao/index.ts
  backend/was/src/auth/dto/oauth-token.dto.ts
  backend/was/src/auth/guard/auth.guard.ts
  backend/was/src/auth/service/auth.service.ts
  backend/was/src/auth/service/kakao.auth.service.ts
  backend/was/src/chat/chat.controller.ts
  backend/was/src/chat/chat.decorators.ts
  backend/was/src/chat/chat.module.ts
  backend/was/src/chat/chat.service.ts
  backend/was/src/chat/dto/chatting-message-response.dto.ts
  backend/was/src/chat/dto/chatting-room-response.dto.ts
  backend/was/src/chat/dto/index.ts
  backend/was/src/chat/entities/chatting-message.entity.ts
  backend/was/src/chat/entities/chatting-room.entity.ts
  backend/was/src/chat/entities/index.ts
  backend/was/src/common/config/cache/redis-cache.module.ts
  backend/was/src/common/config/database/mysql.module.ts
  backend/was/src/common/constants/errors.ts
  backend/was/src/logger/logger.service.ts
  backend/was/src/logger/winston/winston.logger.ts
  backend/was/src/logger/winston/winston.transports.ts
  backend/was/src/main.ts
  backend/was/src/members/dto/create-member.dto.ts
  backend/was/src/members/dto/index.ts
  backend/was/src/members/dto/update-member.dto.ts
  backend/was/src/members/entities/index.ts
  backend/was/src/members/entities/member.entity.ts
  backend/was/src/members/members.module.ts
  backend/was/src/members/members.service.ts
  backend/was/src/tarot/dto/index.ts
  backend/was/src/tarot/dto/tarot-card.dto.ts
  backend/was/src/tarot/dto/tarot-result.dto.ts
  backend/was/src/tarot/entities/index.ts
  backend/was/src/tarot/entities/tarot-card-pack.entity.ts
  backend/was/src/tarot/entities/tarot-result.entity.ts
  backend/was/src/tarot/tarot.controller.ts
  backend/was/src/tarot/tarot.decorators.ts
  backend/was/src/tarot/tarot.module.ts
  backend/was/src/tarot/tarot.service.ts
Labels: BE

#475 Be/bugfix/#474 signal 서버 경로 오류
  backend/signal/package.json
  backend/signal/src/events/events.gateway.spec.ts
  backend/signal/src/mocks/events/logger.mock.ts
  backend/signal/src/mocks/events/room.mock.ts
  backend/signal/src/mocks/events/socket.mock.ts
  backend/signal/src/mocks/events/user.mock.ts
  backend/signal/tsconfig.build.json
  backend/signal/tsconfig.json
Labels: bug, BE

#470 Be/refactor/#469 단위 테스트
  backend/was/package.json
  backend/was/src/chat/chat.service.spec.ts
  backend/was/src/chat/chat.service.ts
  backend/was/src/members/members.servcie.spec.ts
  backend/was/src/members/members.service.ts
  backend/was/src/mocks/chat/chatting-message.mocks.ts
  backend/was/src/mocks/chat/chatting-room.mocks.ts
  backend/was/src/mocks/chat/index.ts
  backend/was/src/mocks/members/index.ts
  backend/was/src/mocks/members/member.mocks.ts
  backend/was/src/mocks/socket/socket.mocks.ts
  backend/was/src/mocks/tarot/index.ts
  backend/was/src/mocks/tarot/tarot-card.mocks.ts
  backend/was/src/mocks/tarot/tarot-result.mocks.ts
  backend/was/src/socket/socket.service.spec.ts
  backend/was/src/socket/socket.service.ts
  backend/was/src/tarot/tarot.controller.ts
  backend/was/src/tarot/tarot.service.spec.ts
  backend/was/src/tarot/tarot.service.ts
  backend/was/tsconfig.build.json
Labels: BE, refactor

#486 Be/bugfix/#485 findTarotCardByCardNo
  backend/was/src/tarot/tarot.controller.ts
Labels: bug, BE

#479 Be/refactor/#478 ci cd 워크플로우 개선
  .github/workflows/blue-green-cd.yml
  backend/Dockerfile.signal
  backend/Dockerfile.was
  backend/compose.blue-deploy.yml
  backend/compose.green-deploy.yml
  backend/deploy.sh
  backend/signal/src/app.controller.ts
  backend/signal/src/app.module.ts
  backend/signal/src/main.ts
  backend/was/src/app.controller.ts
  backend/was/src/app.module.ts
  backend/was/src/common/interceptors/errors.interceptor.ts
  backend/was/src/main.ts
Labels: BE, DevOps, refactor

#489 Be/bugfix/#488 도커 healthcheck
  .github/workflows/blue-green-cd.yml
  backend/compose.blue-deploy.yml
  backend/compose.green-deploy.yml
  backend/deploy.sh
Labels: bug, BE

#483 Fe/feature/#482 fe kakao oAuth 구현
  frontend/public/kakao_login_medium_wide.png
  frontend/src/business/hooks/useAuth/index.ts
  frontend/src/business/hooks/useAuth/useKakaoOAuth.ts
  frontend/src/business/hooks/useAuth/useKakaoOAuthRedirect.ts
  frontend/src/components/Buttons/KakaoLoginButton.tsx
  frontend/src/components/Buttons/index.ts
  frontend/src/constants/kakao.ts
  frontend/src/pages/HomePage/HomePage.tsx
  frontend/src/pages/OAuth2RedirectHandlePage.tsx
  frontend/src/rootRouter.tsx
Labels: feature, FE

#487 Be/feature/#484 웹소켓용 가드 작성
  backend/was/src/app.module.ts
  backend/was/src/auth/auth.controller.ts
  backend/was/src/auth/auth.module.ts
  backend/was/src/auth/guard/index.ts
  backend/was/src/auth/guard/socket-jwt-auth.guard.ts
  backend/was/src/auth/service/auth.service.ts
  backend/was/src/auth/service/kakao.auth.service.ts
  backend/was/src/auth/strategies/jwt.strategy.ts
  backend/was/src/chat/chat.controller.ts
  backend/was/src/chat/chat.service.ts
  backend/was/src/chatbot/clova-studio/clova-studio.service.ts
  backend/was/src/common/config/cache/redis-cache.module.ts
  backend/was/src/common/config/database/mysql.module.ts
  backend/was/src/common/config/jwt/jwt.module.ts
  backend/was/src/common/interceptors/errors.interceptor.ts
  backend/was/src/common/types/socket.ts
  backend/was/src/main.ts
  backend/was/src/socket/socket.gateway.ts
  backend/was/src/socket/socket.service.ts
Labels: BE, task

#494 Be/feature/#493 e2e 세팅 및 타로 모듈 e2e 작성
  backend/was/package.json
  backend/was/src/chat/__mocks__/chatting-message.ts
  backend/was/src/chat/__mocks__/chatting-room.ts
  backend/was/src/chat/chat.controller.ts
  backend/was/src/chat/chat.service.spec.ts
  backend/was/src/chat/chat.service.ts
  backend/was/src/chat/dto/chatting-message.dto.ts
  backend/was/src/chat/dto/chatting-room.dto.ts
  backend/was/src/chat/dto/index.ts
  backend/was/src/members/__mocks__/member.ts
  backend/was/src/members/members.servcie.spec.ts
  backend/was/src/mocks/chat/index.ts
  backend/was/src/mocks/members/index.ts
  backend/was/src/mocks/tarot/index.ts
  backend/was/src/tarot/__mocks__/tarot-card.ts
  backend/was/src/tarot/__mocks__/tarot-result.ts
  backend/was/src/tarot/__mocks__/tarot.service.ts
  backend/was/src/tarot/tarot.service.spec.ts
  backend/was/test/app.e2e-spec.ts
  backend/was/test/jest-e2e.json
  backend/was/test/tarot.e2e-spec.ts
  backend/was/tsconfig.build.json
Labels: BE, task, test

#507 Be/feature/#504 인증 모듈 e2e 테스트
  backend/was/src/auth/__mocks__/kakao.auth.service.ts
  backend/was/src/auth/auth.controller.ts
  backend/was/src/auth/auth.module.ts
  backend/was/src/auth/dto/profile.dto.ts
  backend/was/src/auth/service/auth.service.spec.ts
  backend/was/src/auth/service/auth.service.ts
  backend/was/src/auth/service/kakao.auth.service.ts
  backend/was/src/chat/chat.service.spec.ts
  backend/was/src/common/constants/errors.ts
  backend/was/src/members/__mocks__/member.ts
  backend/was/src/members/dto/create-member.dto.ts
  backend/was/src/members/members.module.ts
  backend/was/src/members/members.servcie.spec.ts
  backend/was/src/members/members.service.ts
  backend/was/src/tarot/tarot.service.spec.ts
  backend/was/test/auth.e2e-spec.ts
  frontend/src/business/hooks/useOverlay/useOverlay.spec.tsx
Labels: feature, BE, test

#501 Be/feature/#496 채팅 모듈 e2e 테스트
  backend/was/package-lock.json
  backend/was/package.json
  backend/was/src/auth/__mocks__/kakao.auth.service.ts
  backend/was/src/auth/auth.controller.ts
  backend/was/src/auth/auth.module.ts
  backend/was/src/auth/dto/profile.dto.ts
  backend/was/src/auth/service/auth.service.spec.ts
  backend/was/src/auth/service/auth.service.ts
  backend/was/src/auth/service/index.ts
  backend/was/src/auth/service/kakao.auth.service.ts
  backend/was/src/chat/__mocks__/chatting-message.ts
  backend/was/src/chat/__mocks__/chatting-room.ts
  backend/was/src/chat/chat.controller.ts
  backend/was/src/chat/chat.service.spec.ts
  backend/was/src/chat/chat.service.ts
  backend/was/src/chat/dto/chatting-message.dto.ts
  backend/was/src/chat/dto/chatting-room.dto.ts
  backend/was/src/chat/entities/chatting-message.entity.ts
  backend/was/src/chat/entities/chatting-room.entity.ts
  backend/was/src/common/constants/errors.ts
  backend/was/src/members/__mocks__/member.ts
  backend/was/src/members/dto/create-member.dto.ts
  backend/was/src/members/entities/member.entity.ts
  backend/was/src/members/members.module.ts
  backend/was/src/members/members.servcie.spec.ts
  backend/was/src/members/members.service.ts
  backend/was/src/socket/socket.service.ts
  backend/was/src/tarot/__mocks__/tarot-card.ts
  backend/was/src/tarot/__mocks__/tarot-result.ts
  backend/was/src/tarot/__mocks__/tarot.service.ts
  backend/was/src/tarot/dto/tarot-result.dto.ts
  backend/was/src/tarot/entities/tarot-card.entity.ts
  backend/was/src/tarot/entities/tarot-result.entity.ts
  backend/was/src/tarot/tarot.service.spec.ts
  backend/was/test/auth.e2e-spec.ts
  backend/was/test/chat.e2e-spec.ts
  backend/was/test/constants.ts
  backend/was/test/tarot.e2e-spec.ts
Labels: feature, BE, test
