Repository boostcampwm2023/web09-MagicConch, pull requests merged in 2024-03, with the labels that each got.

#591 Be/refactor/#589 타로 해설 채팅 기록에 저장 안하기
  backend/was/src/socket/socket.service.ts
Labels: BE, refactor

#585 Fe/bugfix/#584 최초 로그인 시 카카오톡 로그인 후 쿠키가 붙지 않음
  frontend/.eslintrc.cjs
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/business/hooks/auth/useKakaoOAuthRedirect.ts
  frontend/src/utils/env.ts
Labels: bug, FE

#588 Be/bugfix/#587 채팅 메시지 조회 시 카드도 같이 보여야 함
  .github/workflows/blue-green-cd.yml
  backend/Dockerfile.nginx
  backend/was/package.json
  backend/was/src/auth/service/auth.service.spec.ts
  backend/was/src/chat/chat.service.spec.ts
  backend/was/src/chat/chat.service.ts
  backend/was/src/chat/entities/chatting-message.entity.ts
  backend/was/src/chat/entities/chatting-room.entity.ts
  backend/was/src/common/types/socket.ts
  backend/was/src/socket/socket.service.ts
  backend/was/src/tarot/tarot.service.ts
  backend/was/test/chat.e2e-spec.ts
Labels: bug, BE

#597 Fe/bugfix/#593 #594 #595 #596 UI 버그 픽스
  frontend/src/business/hooks/sidebar/useSidebar.tsx
  frontend/src/components/common/Background/Background.tsx
  frontend/src/components/common/ChatContainer/ChatList/ChatList.tsx
  frontend/src/components/common/ChatContainer/MessageBox/Message.tsx
  frontend/src/components/common/ChatContainer/MessageBox/MessageBox.tsx
  frontend/src/pages/AIChatPage/AIChatPage.tsx
  frontend/src/pages/HomePage/HomePage.tsx
Labels: bug, FE

#605 Fe/feature/#580 Ai 타로보기 버튼 클릭 후 닫을 수 있는 기능
  frontend/src/business/hooks/index.ts
  frontend/src/business/hooks/popup/useLoginPopup.tsx
  frontend/src/business/hooks/useOutSideClickEvent.ts
  frontend/src/components/common/Popup/LoginPopup.tsx
Labels: feature, FE

#599 Be/feature/#598 사용자 api 및 서비스 구현
  backend/was/.eslintrc.js
  backend/was/jest-e2e.config.js
  backend/was/jest-unit.config.js
  backend/was/jest.config.js
  backend/was/jest.config.json
  backend/was/package.json
  backend/was/src/auth/dto/auth-status.dto.ts
  backend/was/src/auth/service/auth.service.spec.ts
  backend/was/src/auth/service/auth.service.ts
  backend/was/src/chat/chat.service.spec.ts
  backend/was/src/chat/chat.service.ts
  backend/was/src/chat/dto/chatting-message.dto.ts
  backend/was/src/chat/dto/chatting-room.dto.ts
  backend/was/src/chat/dto/update-chatting-room.dto.ts
  backend/was/src/exceptions/codemap/members-codemap.ts
  backend/was/src/members/dto/create-member.dto.ts
  backend/was/src/members/dto/member.dto.ts
  backend/was/src/members/members.controller.ts
  backend/was/src/members/members.decorators.ts
  backend/was/src/members/members.module.ts
  backend/was/src/members/members.service.spec.ts
  backend/was/src/members/members.service.ts
  backend/was/src/tarot/dto/tarot-result.dto.ts
  backend/was/src/tarot/tarot.service.spec.ts
  backend/was/src/tarot/tarot.service.ts
  backend/was/test/members.e2e-spec.ts
Labels: feature, BE

#609 Fe/bugfix/#601 told 피드백이 안 뜨는 문제
  frontend/index.html
  frontend/src/business/hooks/useUserFeedback.tsx
  frontend/src/business/services/TOLD.ts
  frontend/src/constants/urls.ts
Labels: bug, FE

#608 Fe/feature/#602 카카오톡 로그아웃 기능
  backend/was/src/auth/auth.controller.ts
  frontend/src/business/hooks/auth/useKakaoOAuth.ts
  frontend/src/business/hooks/auth/useKakaoOAuthRedirect.ts
  frontend/src/components/aiChatPage/ChatLogContainer/ChatLogContainer.tsx
  frontend/src/components/common/Buttons/KakaoLoginoutButton.tsx
  frontend/src/components/common/Header/Header.tsx
  frontend/src/constants/kakao.ts
  frontend/src/pages/AIChatPage/AIChatPage.tsx
Labels: feature, FE
