Repository boostcampwm2023/web09-MagicConch, pull requests merged in 2024-02, with the labels that each got.

#513 Be/refactor/#512 swagger 문서 업데이트
  backend/deploy.sh
  backend/was/package-lock.json
  backend/was/package.json
  backend/was/src/app.controller.ts
  backend/was/src/app.decorators.ts
  backend/was/src/auth/auth.controller.ts
  backend/was/src/auth/auth.decorators.ts
  backend/was/src/auth/dto/auth-status.dto.ts
  backend/was/src/auth/dto/index.ts
  backend/was/src/chat/chat.decorators.ts
  backend/was/src/chat/chat.service.ts
  backend/was/src/main.ts
  backend/was/src/tarot/tarot.decorators.ts
Labels: BE, refactor

#526 Be/refactor/#478 ci/cd 워크플로우 개선
  .github/workflows/blue-green-cd.yml
  .github/workflows/build-backend.yml
  backend/compose.blue-build.yml
  backend/compose.blue-deploy.yml
  backend/compose.cache-export.yml
  backend/compose.green-build.yml
  backend/compose.green-deploy.yml
Labels: BE, DevOps, refactor

#523 Be/feature/#522 데이터베이스 최적화
  backend/was/src/auth/__mocks__/kakao.auth.service.ts
  backend/was/src/auth/auth.controller.ts
  backend/was/src/auth/service/auth.service.spec.ts
  backend/was/src/auth/service/auth.service.ts
  backend/was/src/auth/service/kakao.auth.service.ts
  backend/was/src/chat/chat.service.spec.ts
  backend/was/src/chat/chat.service.ts
  backend/was/src/chat/chatting-info.interface.ts
  backend/was/src/chat/entities/chatting-message.entity.ts
  backend/was/src/chat/entities/chatting-room.entity.ts
  backend/was/src/common/constants/etc.ts
  backend/was/src/members/dto/create-member.dto.ts
  backend/was/src/members/entities/member.entity.ts
  backend/was/src/tarot/dto/tarot-card.dto.ts
  backend/was/src/tarot/entities/tarot-card.entity.ts
  backend/was/src/tarot/entities/tarot-result.entity.ts
  backend/was/src/tarot/tarot.service.spec.ts
  backend/was/src/tarot/tarot.service.ts
  backend/was/test/chat.e2e-spec.ts
  backend/was/test/tarot.e2e-spec.ts
Labels: feature, BE

#533 Devops/bugfix/#532 pr 라벨 설정 및 이슈 상태 변경 오류
  .github/workflows/add-issue-to-project-automatically.yml
  .github/workflows/configure-pr-automatically.yml
Labels: bug, DevOps

#535 Fe/bugfix/#534 윈도우에서 height이 맞지 않는 문제 해결
  frontend/package.json
  frontend/pnpm-lock.yaml
Labels: bug, FE

#538 Fe/bugfix/#524 sidebar 관련버그 수정
  frontend/src/business/hooks/sidebar/useSidebar.tsx
  frontend/src/components/aiChatPage/ChatLogContainer/ChatLogContainer.tsx
  frontend/src/components/common/Background/Background.tsx
  frontend/src/components/common/ChatContainer/ChatContainer.tsx
  frontend/src/components/common/Header/Header.tsx
  frontend/src/components/common/Header/HeaderRight.tsx
  frontend/src/components/common/Header/index.ts
  frontend/src/pages/AIChatPage/AIChatPage.tsx
  frontend/src/pages/HomePage/HomePage.tsx
  frontend/src/pages/HumanChatPage/HumanChatPage.tsx
  frontend/src/utils/random.ts
Labels: bug, FE

#537 Be/feature/#536 채팅방 조회 시 생성일자를 기준으로 그룹화하여 전송
  backend/was/src/chat/chat.controller.ts
  backend/was/src/chat/chat.service.spec.ts
  backend/was/src/chat/chat.service.ts
  backend/was/src/chat/dto/chatting-room.dto.ts
  backend/was/src/chat/entities/chatting-message.entity.ts
  backend/was/test/auth.e2e-spec.ts
  backend/was/test/chat.e2e-spec.ts
  backend/was/test/common/constants.ts
  backend/was/test/common/database/sqlite.module.ts
  backend/was/test/tarot.e2e-spec.ts
Labels: feature, BE

#546 Fe/bugfix,refactor/#520 채팅 페이지를 나왔을 때 카메라 권한이 꺼지도록 수정
  backend/signal/src/events/events.gateway.spec.ts
  backend/signal/src/events/events.gateway.ts
  frontend/__mocks__/zustand.ts
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/business/hooks/webRTC/__tests__/useControllMedia.spec.ts
  frontend/src/business/hooks/webRTC/__tests__/useDataChannel.spec.ts
  frontend/src/business/hooks/webRTC/__tests__/useDataChannelEventListener.spec.ts
  frontend/src/business/hooks/webRTC/__tests__/useMedia.spec.ts
  frontend/src/business/hooks/webRTC/__tests__/useMediaStream.spec.ts
  frontend/src/business/hooks/webRTC/__tests__/useStreamVideoRef.spec.ts
  frontend/src/business/hooks/webRTC/__tests__/useWebRTC.spec.ts
  frontend/src/business/hooks/webRTC/index.ts
  frontend/src/business/hooks/webRTC/useControllMedia.ts
  frontend/src/business/hooks/webRTC/useDataChannelEventListener.ts
  frontend/src/business/hooks/webRTC/useMedia.ts
  frontend/src/business/hooks/webRTC/useMediaStream.ts
  frontend/src/business/hooks/webRTC/useStreamVideoRef.tsx
  frontend/src/business/hooks/webRTC/useWebRTC.ts
  frontend/src/business/services/Media.ts
  frontend/src/business/services/Socket.ts
  frontend/src/business/services/WebRTC.ts
  frontend/src/business/services/__mocks__/WebRTC.ts
  frontend/src/business/services/__tests__/Media.spec.ts
  frontend/src/business/services/__tests__/Socket.spec.ts
  frontend/src/business/services/__tests__/WebRTC.spec.ts
  frontend/src/components/common/TarotSpread/TarotSpread.tsx
  frontend/src/components/humanChatPage/CamBox/CamBox.tsx
  frontend/src/components/humanChatPage/CamContainer/CamContainer.tsx
  frontend/src/components/humanChatPage/ProfileSetting/ProfileSetting.tsx
  frontend/src/mocks/webRTC/mediaStreamMock.ts
  frontend/src/pages/HumanChatPage/ChattingPage.tsx
  frontend/src/pages/HumanChatPage/HumanChatPage.tsx
  frontend/src/pages/HumanChatPage/SettingPage.tsx
  frontend/src/pages/HumanChatPage/hooks/useCreateJoinRoomPasswordPopup.ts
  frontend/src/pages/HumanChatPage/hooks/useHumanChatPageState.tsx
  frontend/src/stores/zustandStores/index.ts
  frontend/src/stores/zustandStores/useMediaInfo.ts
  frontend/src/stores/zustandStores/useMediaStreamStore.ts
  frontend/src/tailwind.css
  frontend/tsconfig.json
Labels: bug, FE, refactor

#545 Devops/bugfix,refactor/#231 #544 release pr 오류 해결 및 규칙 변경
  .github/pr-labels.yml
  .github/workflows/add-issue-to-project.yml
  .github/workflows/blue-green-cd.yml
  .github/workflows/close-issue.yml
  .github/workflows/configure-pr.yml
Labels: bug, DevOps, refactor

#550 Devops/bugfix/#549 pr 설정 액션이 멈추지 않음
  .github/workflows/configure-pr.yml
Labels: bug, DevOps

#557 Fe/feature/#551 told 다시 적용하기
  frontend/src/business/hooks/chatMessage/useAiChatMessage.ts
  frontend/src/business/hooks/index.ts
  frontend/src/business/hooks/useTOLD.tsx
  frontend/src/business/hooks/useUserFeedback.tsx
  frontend/src/business/services/SocketManager/AISocketManager.ts
  frontend/src/business/services/SocketManager/HumanSocketManager.ts
  frontend/src/business/services/TOLD.ts
  frontend/src/constants/messages.ts
Labels: feature, FE

#561 Fe/bugfix/#553 홈 화면 갔다가 돌아오면 소켓 에러가 나는 문제
  frontend/src/pages/HomePage/HomePage.tsx
  frontend/src/pages/HomePage/hooks/index.ts
  frontend/src/pages/HomePage/hooks/useReset.ts
Labels: bug, FE

#562 Devops/feature/#558 브랜치명 강제
  .github/workflows/assert-branch-naming.yml
  .github/workflows/configure-pr.yml
Labels: feature, DevOps

#556 Devops/feature/#555 release drafter 도입
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: feature, DevOps

#563 Fe/bugfix/#552 ai input bar가 작아지는 현상
  frontend/src/business/hooks/sidebar/useSidebar.tsx
  frontend/src/components/common/ChatContainer/ChatContainer.tsx
  frontend/src/pages/AIChatPage/AIChatPage.tsx
Labels: bug, FE

#571 Fe,be/feature/#567 fe,be 소켓 이벤트 타입 공유하기
  @types/event.d.ts
  backend/signal/package-lock.json
  backend/signal/package.json
  backend/signal/src/events/events.gateway.ts
  backend/signal/src/events/type.ts
  backend/signal/tsconfig.json
  backend/was/package-lock.json
  backend/was/package.json
  backend/was/src/chatbot/clova-studio/clova-studio.service.spec.ts
  backend/was/src/common/types/socket.ts
  backend/was/src/socket/socket.gateway.ts
  backend/was/src/socket/socket.service.ts
  backend/was/tsconfig.json
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/business/services/SocketManager/AISocketManager.ts
  frontend/src/business/services/SocketManager/HumanSocketManager.ts
  frontend/src/business/services/SocketManager/SocketManager.ts
  frontend/src/business/services/SocketManager/__tests__/HumanSocketManager.spec.ts
  frontend/tsconfig.json
  packages/ai-socketio-event/LICENSE
  packages/ai-socketio-event/README.md
  packages/ai-socketio-event/index.d.ts
  packages/ai-socketio-event/index.js
  packages/ai-socketio-event/package.json
  packages/ai-socketio-event/pnpm-lock.yaml
  packages/human-socketio-event/LICENSE
  packages/human-socketio-event/README.md
  packages/human-socketio-event/index.d.ts
  packages/human-socketio-event/index.js
  packages/human-socketio-event/package.json
Labels: feature, FE, BE

#566 Be/bugfix/#565 ssl 인증서 만료
  .github/workflows/blue-green-cd.yml
  backend/Dockerfile.nginx
  backend/compose.blue-deploy.yml
  backend/compose.green-deploy.yml
Labels: bug, BE

#570 Be/refactor/#569 api 커스텀 에러 정의
  backend/was/src/auth/__mocks__/kakao.auth.service.ts
  backend/was/src/auth/service/kakao.auth.service.ts
  backend/was/src/chat/chat.service.spec.ts
  backend/was/src/chat/chat.service.ts
  backend/was/src/common/constants/apis.ts
  backend/was/src/common/constants/errors.ts
  backend/was/src/exceptions/codemap/auth-codemap.ts
  backend/was/src/exceptions/codemap/chat-codemap.ts
  backend/was/src/exceptions/codemap/index.ts
  backend/was/src/exceptions/codemap/tarot-codemap.ts
  backend/was/src/exceptions/codemap/type.ts
  backend/was/src/exceptions/custom-exception.ts
  backend/was/src/exceptions/index.ts
  backend/was/src/exceptions/metadata.ts
  backend/was/src/tarot/tarot.service.spec.ts
  backend/was/src/tarot/tarot.service.ts
  backend/was/test/auth.e2e-spec.ts
Labels: BE, refactor

#564 Fe/feature/#560 error boundary적용
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/App.tsx
  frontend/src/business/services/SocketManager/SocketManager.ts
  frontend/src/errors/APIErrorBoundary.tsx
  frontend/src/errors/UnknownErrorBoundary.tsx
  frontend/src/errors/index.ts
  frontend/src/pages/ErrorPage/SomethingWrongErrorPage.tsx
  frontend/src/pages/ErrorPage/index.ts
  frontend/src/router.tsx
Labels: feature, FE

#576 Fe/bugfix/#575 게스트가 방입장도중 취소 누를시 아무런 작동을 하지않음
  frontend/src/business/hooks/webRTC/useSignalingSocket.ts
  frontend/src/pages/HumanChatPage/hooks/useCreateJoinRoomPasswordPopup.ts
Labels: bug, FE

#578 Devops/refactor/#478 ci cd 워크플로우 개선
  backend/Dockerfile.nginx
Labels: DevOps, refactor

#586 Be/bugfix/#584 최초 로그인 시 카카오톡 로그인 후 쿠키가 붙지 않음
  backend/was/src/auth/auth.controller.ts
Labels: bug, BE
